// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: livro-service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_livro_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livro_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_livro_service_proto_rawDescGZIP(), []int{0}
}

type FindByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FindByIdRequest) Reset() {
	*x = FindByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_livro_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByIdRequest) ProtoMessage() {}

func (x *FindByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livro_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByIdRequest.ProtoReflect.Descriptor instead.
func (*FindByIdRequest) Descriptor() ([]byte, []int) {
	return file_livro_service_proto_rawDescGZIP(), []int{1}
}

func (x *FindByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type LivroRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Titulo string  `protobuf:"bytes,1,opt,name=titulo,proto3" json:"titulo,omitempty"`
	Isbn   string  `protobuf:"bytes,2,opt,name=isbn,proto3" json:"isbn,omitempty"`
	Autor  string  `protobuf:"bytes,3,opt,name=autor,proto3" json:"autor,omitempty"`
	Preco  float64 `protobuf:"fixed64,4,opt,name=preco,proto3" json:"preco,omitempty"`
}

func (x *LivroRequest) Reset() {
	*x = LivroRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_livro_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LivroRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LivroRequest) ProtoMessage() {}

func (x *LivroRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livro_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LivroRequest.ProtoReflect.Descriptor instead.
func (*LivroRequest) Descriptor() ([]byte, []int) {
	return file_livro_service_proto_rawDescGZIP(), []int{2}
}

func (x *LivroRequest) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

func (x *LivroRequest) GetIsbn() string {
	if x != nil {
		return x.Isbn
	}
	return ""
}

func (x *LivroRequest) GetAutor() string {
	if x != nil {
		return x.Autor
	}
	return ""
}

func (x *LivroRequest) GetPreco() float64 {
	if x != nil {
		return x.Preco
	}
	return 0
}

type Livro struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Titulo string  `protobuf:"bytes,2,opt,name=titulo,proto3" json:"titulo,omitempty"`
	Isbn   string  `protobuf:"bytes,3,opt,name=isbn,proto3" json:"isbn,omitempty"`
	Autor  string  `protobuf:"bytes,4,opt,name=autor,proto3" json:"autor,omitempty"`
	Preco  float64 `protobuf:"fixed64,5,opt,name=preco,proto3" json:"preco,omitempty"`
}

func (x *Livro) Reset() {
	*x = Livro{}
	if protoimpl.UnsafeEnabled {
		mi := &file_livro_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Livro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Livro) ProtoMessage() {}

func (x *Livro) ProtoReflect() protoreflect.Message {
	mi := &file_livro_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Livro.ProtoReflect.Descriptor instead.
func (*Livro) Descriptor() ([]byte, []int) {
	return file_livro_service_proto_rawDescGZIP(), []int{3}
}

func (x *Livro) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Livro) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

func (x *Livro) GetIsbn() string {
	if x != nil {
		return x.Isbn
	}
	return ""
}

func (x *Livro) GetAutor() string {
	if x != nil {
		return x.Autor
	}
	return ""
}

func (x *Livro) GetPreco() float64 {
	if x != nil {
		return x.Preco
	}
	return 0
}

type LivroList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Livros []*Livro `protobuf:"bytes,1,rep,name=livros,proto3" json:"livros,omitempty"`
}

func (x *LivroList) Reset() {
	*x = LivroList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_livro_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LivroList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LivroList) ProtoMessage() {}

func (x *LivroList) ProtoReflect() protoreflect.Message {
	mi := &file_livro_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LivroList.ProtoReflect.Descriptor instead.
func (*LivroList) Descriptor() ([]byte, []int) {
	return file_livro_service_proto_rawDescGZIP(), []int{4}
}

func (x *LivroList) GetLivros() []*Livro {
	if x != nil {
		return x.Livros
	}
	return nil
}

var File_livro_service_proto protoreflect.FileDescriptor

var file_livro_service_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6c, 0x69, 0x76, 0x72, 0x6f, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6c, 0x69, 0x76, 0x72, 0x6f, 0x22, 0x0e, 0x0a, 0x0c,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x21, 0x0a, 0x0f,
	0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x66, 0x0a, 0x0c, 0x4c, 0x69, 0x76, 0x72, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x74, 0x69, 0x74, 0x75, 0x6c, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x74, 0x69, 0x74, 0x75, 0x6c, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x73, 0x62, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x73, 0x62, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x61,
	0x75, 0x74, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x75, 0x74, 0x6f,
	0x72, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x65, 0x63, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x05, 0x70, 0x72, 0x65, 0x63, 0x6f, 0x22, 0x6f, 0x0a, 0x05, 0x4c, 0x69, 0x76, 0x72, 0x6f,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x74, 0x69, 0x74, 0x75, 0x6c, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x74, 0x69, 0x74, 0x75, 0x6c, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x73, 0x62, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x73, 0x62, 0x6e, 0x12, 0x14, 0x0a, 0x05,
	0x61, 0x75, 0x74, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x75, 0x74,
	0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x65, 0x63, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x05, 0x70, 0x72, 0x65, 0x63, 0x6f, 0x22, 0x31, 0x0a, 0x09, 0x4c, 0x69, 0x76, 0x72,
	0x6f, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x06, 0x6c, 0x69, 0x76, 0x72, 0x6f, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6c, 0x69, 0x76, 0x72, 0x6f, 0x2e, 0x4c, 0x69,
	0x76, 0x72, 0x6f, 0x52, 0x06, 0x6c, 0x69, 0x76, 0x72, 0x6f, 0x73, 0x32, 0xd3, 0x01, 0x0a, 0x0c,
	0x4c, 0x69, 0x76, 0x72, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x30, 0x0a, 0x08,
	0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x49, 0x64, 0x12, 0x16, 0x2e, 0x6c, 0x69, 0x76, 0x72, 0x6f,
	0x2e, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x0c, 0x2e, 0x6c, 0x69, 0x76, 0x72, 0x6f, 0x2e, 0x4c, 0x69, 0x76, 0x72, 0x6f, 0x12, 0x32,
	0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x79, 0x49, 0x64, 0x12, 0x16, 0x2e, 0x6c,
	0x69, 0x76, 0x72, 0x6f, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x6c, 0x69, 0x76, 0x72, 0x6f, 0x2e, 0x4c, 0x69, 0x76,
	0x72, 0x6f, 0x12, 0x30, 0x0a, 0x07, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x12, 0x13, 0x2e,
	0x6c, 0x69, 0x76, 0x72, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x10, 0x2e, 0x6c, 0x69, 0x76, 0x72, 0x6f, 0x2e, 0x4c, 0x69, 0x76, 0x72, 0x6f,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x13,
	0x2e, 0x6c, 0x69, 0x76, 0x72, 0x6f, 0x2e, 0x4c, 0x69, 0x76, 0x72, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x6c, 0x69, 0x76, 0x72, 0x6f, 0x2e, 0x4c, 0x69, 0x76, 0x72,
	0x6f, 0x42, 0x0d, 0x5a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_livro_service_proto_rawDescOnce sync.Once
	file_livro_service_proto_rawDescData = file_livro_service_proto_rawDesc
)

func file_livro_service_proto_rawDescGZIP() []byte {
	file_livro_service_proto_rawDescOnce.Do(func() {
		file_livro_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_livro_service_proto_rawDescData)
	})
	return file_livro_service_proto_rawDescData
}

var file_livro_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_livro_service_proto_goTypes = []interface{}{
	(*EmptyRequest)(nil),    // 0: livro.EmptyRequest
	(*FindByIdRequest)(nil), // 1: livro.FindByIdRequest
	(*LivroRequest)(nil),    // 2: livro.LivroRequest
	(*Livro)(nil),           // 3: livro.Livro
	(*LivroList)(nil),       // 4: livro.LivroList
}
var file_livro_service_proto_depIdxs = []int32{
	3, // 0: livro.LivroList.livros:type_name -> livro.Livro
	1, // 1: livro.LivroService.FindById:input_type -> livro.FindByIdRequest
	1, // 2: livro.LivroService.DeleteById:input_type -> livro.FindByIdRequest
	0, // 3: livro.LivroService.FindAll:input_type -> livro.EmptyRequest
	2, // 4: livro.LivroService.Create:input_type -> livro.LivroRequest
	3, // 5: livro.LivroService.FindById:output_type -> livro.Livro
	3, // 6: livro.LivroService.DeleteById:output_type -> livro.Livro
	4, // 7: livro.LivroService.FindAll:output_type -> livro.LivroList
	3, // 8: livro.LivroService.Create:output_type -> livro.Livro
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_livro_service_proto_init() }
func file_livro_service_proto_init() {
	if File_livro_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_livro_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_livro_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_livro_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LivroRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_livro_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Livro); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_livro_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LivroList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_livro_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_livro_service_proto_goTypes,
		DependencyIndexes: file_livro_service_proto_depIdxs,
		MessageInfos:      file_livro_service_proto_msgTypes,
	}.Build()
	File_livro_service_proto = out.File
	file_livro_service_proto_rawDesc = nil
	file_livro_service_proto_goTypes = nil
	file_livro_service_proto_depIdxs = nil
}
